/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm") version Versions.kotlin
    id("org.jmailen.kotlinter") version Versions.kotlinter
    // id("com.gradle.plugin-publish") version "0.9.10"
    `maven-publish`
    `java-gradle-plugin`
    `build-scan`
    id("gradle.site") version Versions.site
}

val webUrl = ""
val githubUrl = "https://github.optum.com/ATC/${project.name}.git"

buildScan {
    termsOfServiceUrl = "https://gradle.com/terms-of-service"
    termsOfServiceAgree = "yes"

    publishAlways()
}

site {
    outputDir.set(file("$rootDir/docs"))
    websiteUrl.set(webUrl)
    vcsUrl.set(githubUrl)
}

gradlePlugin {
    plugins {
        create("GsqlPlugin") {
            id = "com.optum.gradle.tigergraph"
            implementationClass = "com.optum.gradle.tigergraph.GsqlPlugin"
        }

    }
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenLocal()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    /*
    implementation("com.tigergraph.client:Driver:2.1.7")
    implementation("commons-cli:commons-cli:1.4")
    implementation("jline:jline:2.11")
    implementation("org.json:json:20180130")
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    */

    runtime("com.tigergraph.client:Driver:2.1.7")
    runtime("commons-cli:commons-cli:1.4")
    runtime("jline:jline:2.11")
    runtime("org.json:json:20180130")
    runtime("javax.xml.bind:jaxb-api:2.3.1")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

group = "com.optum.gradle.tigergraph"
version = "0.1.0"

publishing {
    repositories {}
    publications {}
}
