:icla: link:INDIVIDUAL_CONTRIBUTOR_LICENSE.adoc[Individual Contributor License Agreement ("ICL")]
:git-rewrite: link:https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
= Contributing to Giraffle
:toc:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Guidelines

This project has a link:CODE_OF_CONDUCT.md[Code of Conduct]. Participating in
this project requires you to abide by its terms.  Please review our {icla}
prior to submitting changes to the project.  Please direct any questions to
opensource@optum.com.

TIP: Our ICL requires contributors to `sign-off` on each commit.  Adding an
alias to the project will make this easier. ```git config --local
format.signoff true```

[#question]
== Got a Question or Problem?

Take a look in the https://github.com/optum/giraffle/issues[issues].
Maybe your question is already answered.

[#issue]
== Found an Issue?

If you find a bug in the source code or a mistake in the documentation, you can
help us by submitting an issue to our
https://github.com/optum/giraffle/issues[GitHub Issue Tracker]. Even better you
can submit a Pull Request with a fix for the issue you filed.

[#feature]
== Want a Feature?

You can request a new feature by submitting an issue to our
https://github.com/optum/giraffle/issues[GitHub Issue Tracker].
If you would like to implement a new feature then first create a new issue and
discuss it with one of our project maintainers.

[#submit]
== Submission Guidelines

=== Submitting an Issue
Before you submit your issue search the archive, maybe your question was
already answered.

If your issue appears to be a bug, and hasn't been reported, open a new issue.
Help us to maximize the effort we can spend fixing issues and adding new
features, by not reporting duplicate issues.  Providing the following
information will increase the chances of your issue being dealt with quickly:

* **Overview of the Issue** - if an error is being thrown a stack trace helps
* **Motivation for or Use Case** - explain why this is a bug for you
* **Giraffle Version** - is it a named version or from our dev branch
* **Operating System** - Mac, windows? details help
* **Suggest a Fix** - if you can't fix the bug yourself, perhaps you can point
  to what might be causing the problem (line of code or commit)

=== Submitting a Pull Request

==== Paperwork for Pull Requests

Please read this guide and make sure you agree with our {icla}.

* Write good commit messages
* Sign-off every commit `git commit --signoff` or `git commit -s`, as directed
  by the ICL.

NOTE: If you forget to sign a commit, then you'll have to do a bit of rewriting
history. Don't worry. It's pretty easy. If it's the latest commit, you can just
run either `git commit -a -s` or `git commit --amend --signoff` to fix things.
It gets a little trickier if you have to change something farther back in
history but there are some good instructions {git-rewrite}[here] in the
Changing Multiple Commit Messages section.

* <<commit,Reference your issues>> within your commits.

==== Fork Giraffle

Fork the project https://github.com/optum/giraffle/fork[on GitHub] and clone
your copy.

[source,shell]
----
$ git clone git@github.com:username/giraffle.git
$ cd giraffle
$ git remote add upstream git://github.com/optum/giraffle.git
----

All bug fixes and new features go into the dev branch.

We ask that you open an issue in the
https://github.com/optum/giraffle/issues[issue tracker] and get agreement from
at least one of the project maintainers before you start coding.

Nothing is more frustrating than seeing your hard work go to waste because
your vision does not align with that of a project maintainer.

==== Create a branch for your changes

Okay, so you have decided to fix something. Create a feature branch
and start hacking:

[source,shell]
----
$ git checkout -b my-feature-branch -t origin/dev
----

==== Formatting code

We use http://editorconfig.org/[.editorconfig] to configure our editors for
proper code formatting. If you don't use a tool that supports editorconfig be
sure to configure your editor to use the settings equivalent to our
`.editorconfig` file.

[#commit]
==== Commit your changes

Make sure git knows your name and email address:

[source,shell]
----
$ git config user.name "J. Random User"
$ git config user.email "j.random.user@example.com"
----

NOTE: Signing-Off on your commit is agreeing with our ICL and attesting that
you either wrote or have the rights to contribute the code. The name and email
address must be valid as we cannot accept anonymous contributions.

Writing good commit logs is important. A commit log should describe what
changed and why. Follow these guidelines when writing one:

. Always try to answer the question, "If this commit is merged into master it
  will..."
. The first line should be 50 characters or less and contain a short
  description of the change including the Issue number prefixed by a hash (#).
. Keep the second line blank.
. Wrap all other lines at 72 columns.

A good commit log looks like this:

----
feature #123: Add interactive shell experience

Body of commit message is a few lines of text, explaining things
in more detail, possibly giving some background about the issue
being fixed, etc etc.

The body of the commit message can be several paragraphs, and
please do proper word-wrap and keep columns shorter than about
72 characters or so. That way `git log` will show things
nicely even when it is indented.
----

The header line should be meaningful; it is what other people see when they
run `git shortlog` or `git log --oneline`.

==== Rebase your repo

Use `git rebase` (not `git merge`) to sync your work from time to time.

[source,shell]
----
$ git fetch upstream
$ git rebase upstream/dev
----


==== Test your code

We are working hard to improve Giraffle's testing. Currently our testing is
focused on integration testing. Please ensure your code doesn't break existing
functionality. Additionally, please ensure any new features you add have proper
tests add as well.

[source,shell]
----
$ ./gradlew integrationTest
----

Make sure that all tests pass. Please, do not submit patches that fail.

==== Push your changes

[source,shell]
----
$ git push origin my-feature-branch
----

==== Submit the pull request

Go to https://github.com/{username}/giraffle and select your feature branch.
Click the `Pull Request` button and fill out the form.

Pull requests are usually reviewed within a few days. If you get comments that
need to be to addressed, apply your changes in a separate commit and push that
to your feature branch. Post a comment in the pull request afterwards; GitHub
does not send out notifications when you add commits to existing pull requests.

That's it! Thank you for your contribution!


==== After your pull request is merged

After your pull request is merged, you can safely delete your branch and pull
the changes from the main (upstream) repository:

* Delete the remote branch on GitHub either through the GitHub web UI or your
  local shell as follows:

[source,shell]
----
git push origin --delete my-feature-branch
----

* Check out the dev branch:

[source,shell]
----
git checkout dev -f
----

* Delete the local branch:

[source,shell]
----
git branch -D my-feature-branch
----

* Update your dev with the latest upstream version:

[source,shell]
----
git pull --ff upstream dev
----
