:maven-metadata: plugins.gradle.org/m2/com/optum/giraffle/giraffle
:travis: https://travis-ci.org/Optum/giraffle
:gradle-plugins-portal: https://plugins.gradle.org/plugin/com.optum.giraffle
:tigergraph-gsql-doc: https://docs.tigergraph.com/dev/using-a-remote-gsql-client
:maven-local-repo: https://maven.apache.org/plugins/maven-install-plugin/examples/specific-local-repo.html
:tiger-bintray: https://bintray.com/beta/#/tigergraphecosys/tgjars
:documentation-site: https://optum.github.io/giraffle/#/
:project-version: 1.3.4

= Giraffle image:{travis}.svg?branch=master["Build Status",link="{travis}"] image:https://img.shields.io/badge/build-scan-green.svg["Build Scan", link="https://gradle.com/s/s6djnnqrmgsq4"] image:https://img.shields.io/maven-metadata/v/https/{maven-metadata}/maven-metadata.xml.svg?label=gradlePluginPortal["Maven Central",link="{gradle-plugins-portal}"]
Gradle Plugin for Tigergraph
Josh Meekhof <joshua_meekhof@optum.com>

:toc:
:homepage: https://github.com/Optum/Giraffle.git

This plugin creates a dsl for Tigergraph. The dsl allows you to describe
connections to a Tigergraph server.

The Giraffle plugin has been published to the Gradle plugins repository. You
may use it by referencing it within your `plugins` block. Please refer to the
<<plugin-use>> section for instructions.

[#plugin-use]
== Using the plugin
Please refer to our {documentation-site}[documentation site, role=external,
window=_blank] for a complete guide.

Like most Gradle plugins, you simply need to add the id to the plugins closure.

[source,gradle,subs="attributes"]
----
plugins {
    id("com.optum.giraffle") version "{project-version}"
}

repositories {
    jcenter()
}
----

[#assist]
== Development Assistance
Fork and clone this repository. After this you should be able to make changes,
compile, test and publish.  The `publishToMavenLocal` will make the plugin
available to your Gradle projects. Add the `mavenLocal()` repository to your
repositories closure.
